export default [
  {
    id: 1,
    img: "./images/card1.jpg",
    reviewCount: 8,
    rating: 5.0,
    country: "Indonesia",
    price: 310,
    status: "SOLD OUT",
    openSpot: 0,
  },
  {
    id: 2,
    img: "./images/card2.jpg",
    reviewCount: 7,
    rating: 4.5,
    country: "America",
    price: 210,
    status: "ONLINE",
    openSpot: 1,
  },
  {
    id: 3,
    img: "./images/card3.jpg",
    reviewCount: 6,
    rating: 4.0,
    country: "Malaysia",
    price: 110,
    status: "SOLD OUT",
    openSpot: 0,
  },
  {
    id: 4,
    img: "./images/card4.jpeg",
    reviewCount: 5,
    rating: 3.5,
    country: "Singapore",
    price: 410,
    status: "ONLINE",
    openSpot: 3,
  },
  {
    id: 5,
    img: "./images/card5.jpeg",
    reviewCount: 4,
    rating: 3,
    country: "United Kingdom",
    price: 410,
    status: "SOLD OUT",
    openSpot: 0,
  },
];
